#!/bin/bash

#$ git config credential.helper store
#$ git push http://example.com/repo.git
#Username: <type your username>
#Password: <type your password>

git add .
echo Podaj nazwę commita:
read name_commit
git commit -m $name_commit
git push -u origin master

echo " " 
echo Zkończono synchronizację.
